"""added imageUrl fields to user and pet

Revision ID: 4e2a8caff072
Revises: fed81feab0c7
Create Date: 2025-10-09 20:08:56.334226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2a8caff072'
down_revision: Union[str, Sequence[str], None] = 'fed81feab0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('imageUrl', sa.String(), nullable=True))
    op.add_column('users', sa.Column('imageUrl', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'imageUrl')
    op.drop_column('pets', 'imageUrl')
    # ### end Alembic commands ###
