"""split scheduledFor into date/time, add appointmentType

Revision ID: a7099fa637f8
Revises: 0f58e801b82b
Create Date: 2025-10-09 22:29:55.442817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7099fa637f8'
down_revision: Union[str, Sequence[str], None] = '0f58e801b82b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('scheduledDate', sa.Date(), nullable=False))
    op.add_column('appointments', sa.Column('scheduledTime', sa.Time(), nullable=False))
    op.add_column('appointments', sa.Column('appointmentType', sa.Enum('CHECKUP', 'VACCINATION', 'GROOMING', 'SURGERY', 'EMERGENCY_CARE', 'TREATMENT', 'CONSULTATION', name='appointmenttype'), nullable=False))
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'RESCHEDULED', name='appointmentstatus'),
               nullable=False)
    op.drop_column('appointments', 'scheduledFor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('scheduledFor', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'RESCHEDULED', name='appointmentstatus'),
               nullable=True)
    op.drop_column('appointments', 'appointmentType')
    op.drop_column('appointments', 'scheduledTime')
    op.drop_column('appointments', 'scheduledDate')
    # ### end Alembic commands ###
