"""added new fields to pets model

Revision ID: fed81feab0c7
Revises: 
Create Date: 2025-10-09 19:05:43.215219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fed81feab0c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('species', sa.String(), nullable=False))
    op.add_column('pets', sa.Column('gender', sa.String(), nullable=False))
    op.add_column('pets', sa.Column('color', sa.String(), nullable=False))
    op.add_column('pets', sa.Column('microchip_number', sa.String(), nullable=True))
    op.add_column('pets', sa.Column('vaccination_status', sa.String(), nullable=True))
    op.add_column('pets', sa.Column('createdAt', sa.DateTime(), nullable=False))

    op.alter_column('pets', 'breed',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pets', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ✅ FIXED: Added explicit cast for PostgreSQL
    op.alter_column('pets', 'weight',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='weight::double precision')

    op.create_unique_constraint(None, 'pets', ['microchip_number'])
    op.drop_column('pets', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pets', type_='unique')
    op.alter_column('pets', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pets', 'breed',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pets', 'weight',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='weight::text')
    op.drop_column('pets', 'createdAt')
    op.drop_column('pets', 'vaccination_status')
    op.drop_column('pets', 'microchip_number')
    op.drop_column('pets', 'color')
    op.drop_column('pets', 'gender')
    op.drop_column('pets', 'species')
    # ### end Alembic commands ###
